/**
 * Datos demo para PRAXEON Web Application
 * Fiel reflejo del mockup UI y arquitectura formal de PRAXEON 1.0.
 */

export const INITIAL_SESSION = {
  sessionId: "7f3a2c",
  status: "Active",
  agent: "CodingAgent",
  goal: "Fix authentication bug in the API",
  metrics: {
    totalDecisions: 12,
    allowed: 8,
    blocked: 3,
    review: 1,
  },
  runtime: {
    provider: "JEV + LAYA",
    version: "v1.0.0",
    latencyP50: "93ms",
    executionTime: "—",
  },
};

export const INITIAL_NODES = [
  // Inicio
  {
    id: "start",
    label: "Start",
    type: "start",
    status: "SYSTEM",
    x: 420,
    y: 30,
    parentId: null,
  },
  // Secuencia inicial
  {
    id: "node-1",
    label: "1. Analyze issue",
    subtitle: "14:32:01 · LLM (JEV)",
    type: "step",
    status: "ALLOW",
    action: "analyze_codebase",
    x: 420,
    y: 90,
    parentId: "start",
  },
  {
    id: "node-2",
    label: "2. Plan solution",
    subtitle: "14:32:05 · LLM (JEV)",
    type: "step",
    status: "ALLOW",
    action: "create_remediation_plan",
    x: 420,
    y: 150,
    parentId: "node-1",
  },
  {
    id: "node-3",
    label: "3. Select tools",
    subtitle: "14:32:08 · LLM (JEV)",
    type: "step",
    status: "ALLOW",
    action: "select_tooling",
    x: 420,
    y: 210,
    parentId: "node-2",
  },
  {
    id: "node-4",
    label: "4. Read file",
    subtitle: "14:32:12 · Tool (Filesystem)",
    type: "step",
    status: "ALLOW",
    action: "read_file: auth/middleware.py",
    x: 420,
    y: 270,
    parentId: "node-3",
  },
  {
    id: "node-5",
    label: "5. Propose changes",
    subtitle: "14:32:18 · LLM (LAYA)",
    type: "hub",
    status: "PROPOSE",
    action: "git push origin main",
    x: 420,
    y: 340,
    parentId: "node-4",
  },

  // Rama Izquierda (Branch A - Tests & Edit)
  {
    id: "node-6",
    label: "Read docs",
    subtitle: "14:32:20 · Tool (Docs)",
    type: "step",
    status: "ALLOW",
    action: "read_docs: security_oauth2.md",
    x: 230,
    y: 420,
    parentId: "node-5",
  },
  {
    id: "node-7",
    label: "Edit file",
    subtitle: "14:32:27 · Tool (Filesystem)",
    type: "step",
    status: "ALLOW",
    action: "edit_file: auth/middleware.py",
    x: 230,
    y: 480,
    parentId: "node-6",
  },
  {
    id: "node-8",
    label: "Run tests",
    subtitle: "14:32:31 · Tool (Terminal)",
    type: "step",
    status: "BLOCK",
    action: "pytest tests/test_auth.py",
    x: 230,
    y: 540,
    parentId: "node-7",
  },
  {
    id: "node-9",
    label: "Tests passed",
    subtitle: "14:32:36 · 6/6",
    type: "leaf",
    status: "ALLOW",
    action: "test_verification_passed",
    x: 160,
    y: 610,
    parentId: "node-8",
  },
  {
    id: "node-10",
    label: "Tests failed",
    subtitle: "14:32:41 · 2/6",
    type: "leaf",
    status: "BLOCK",
    action: "test_verification_failed",
    x: 300,
    y: 610,
    parentId: "node-8",
  },

  // Rama Central (Branch B - Web & Approval)
  {
    id: "node-11",
    label: "Search web",
    subtitle: "14:32:22 · Tool (Web)",
    type: "step",
    status: "REVIEW",
    action: "search_web: oauth2 invalid token response RFC",
    x: 460,
    y: 420,
    parentId: "node-5",
  },
  {
    id: "node-12",
    label: "Ask for confirmation",
    subtitle: "14:32:24 · Policy",
    type: "step",
    status: "REVIEW",
    action: "policy_human_intervention_request",
    x: 460,
    y: 480,
    parentId: "node-11",
  },
  {
    id: "node-13",
    label: "Waiting for approval",
    subtitle: "14:32:24",
    type: "leaf",
    status: "PENDING",
    action: "awaiting_user_token",
    x: 460,
    y: 540,
    parentId: "node-12",
  },

  // Rama Derecha (Branch C - Config & Block)
  {
    id: "node-14",
    label: "Modify config",
    subtitle: "14:32:26 · Tool (Env)",
    type: "step",
    status: "REVIEW",
    action: "write_env: .env.production",
    x: 650,
    y: 420,
    parentId: "node-5",
  },
  {
    id: "node-15",
    label: "Blocked",
    subtitle: "14:32:28 · Policy",
    type: "leaf",
    status: "BLOCK",
    action: "policy_prevented_production_edit",
    x: 650,
    y: 480,
    parentId: "node-14",
  },
];

export const INITIAL_DECISIONS_MAP = {
  "node-5": {
    decisionId: "d_7f3a2c-5",
    sequence: 5,
    status: "BLOCKED",
    actionCommand: "git push origin main",
    tool: "git",
    provider: "JEV",
    model: "Claude-3.5-sonnet",
    riskLevel: "HIGH",
    riskScore: 0.82,
    semanticEvaluation: [
      { provider: "LAYA", score: 0.81, verdict: "ALLOW" },
      { provider: "TypeSafe", score: 0.64, verdict: "REVIEW" },
    ],
    policyDecision: {
      status: "Requires confirmation",
      requiresConfirmation: true,
      rulesActivated: ["EgressPolicy", "PathContainment", "DoubleVerification"],
      reasonCodes: ["REQUIRE_HUMAN_CONFIRMATION", "EGRESS_MUTATION_RISK"],
      precedence: "Deterministic Safety Precedence (Hard Block > Human Gate > Auto Allow)",
    },
    capability: {
      issued: false,
      statusText: "Not issued",
      token: null,
      expiresAt: null,
    },
    reason: "High risk action (git push) requires human confirmation according to policy rules.",
    evidenceTab: {
      groundingScore: 0.72,
      claimCount: 3,
      claims: [
        "Local commits are ahead of origin/main by 1 commit.",
        "Branch protection rules mandate verified sign-off.",
        "Remote repository is https://github.com/AndreuVM/praxeon.git"
      ],
      observationsUsed: ["obs_git_status", "obs_git_diff", "obs_origin_url"],
      freshness: "live (14:32:18 UTC)",
    },
    receiptTab: {
      decisionId: "d_7f3a2c-5",
      sessionId: "7f3a2c",
      actionHash: "sha256:7e9b04fc41a7d6568297b83321588632a488c0352ef2bc560ec0a8c27e852d43",
      stateHash: "sha256:4b81c201a096180373ad412e8473e6a71e8bfb510ca1c1696a60db9372179b02",
      nonce: "non_89a01f7c11",
      signature: "hmac-sha256:39a7b212f008cb042aaefc32986423a884efbb5c",
      hasValidHmac: true,
      expiresAt: "14:37:18 UTC (5 min TTL)",
      isExpired: false,
    },
    relatedDecisions: [
      { id: "#7f3a2b-4", tool: "Read file", verdict: "ALLOW" },
      { id: "#7f3a2b-3", tool: "Edit file", verdict: "ALLOW" },
    ],
  },
  "node-8": {
    decisionId: "d_7f3a2c-8",
    sequence: 8,
    status: "BLOCKED",
    actionCommand: "pytest tests/test_auth.py",
    tool: "Terminal",
    provider: "JEV",
    model: "Claude-3.5-sonnet",
    riskLevel: "MEDIUM",
    riskScore: 0.45,
    semanticEvaluation: [
      { provider: "LAYA", score: 0.89, verdict: "ALLOW" },
      { provider: "TypeSafe", score: 0.84, verdict: "ALLOW" },
    ],
    policyDecision: {
      status: "Blocked by test failure",
      requiresConfirmation: false,
      rulesActivated: ["RegressionAssertionPolicy"],
      reasonCodes: ["TEST_SUITE_REGRESSION"],
      precedence: "Deterministic Safety Precedence",
    },
    capability: {
      issued: false,
      statusText: "Revoked upon failure",
      token: null,
      expiresAt: null,
    },
    reason: "2 out of 6 test assertions failed in test_auth.py during validation run.",
    evidenceTab: {
      groundingScore: 0.94,
      claimCount: 2,
      claims: [
        "Test output contains assertion failure at line 42.",
        "Token expiration returns HTTP 500 instead of HTTP 401."
      ],
      observationsUsed: ["pytest_stdout_trace"],
      freshness: "live (14:32:31 UTC)",
    },
    receiptTab: {
      decisionId: "d_7f3a2c-8",
      sessionId: "7f3a2c",
      actionHash: "sha256:91ca0f41ab788295b927acde",
      stateHash: "sha256:22bc4177d541258673a901fe",
      nonce: "non_4821ca31",
      signature: "hmac-sha256:bbf824128a10738495ff",
      hasValidHmac: true,
      expiresAt: "14:37:31 UTC",
      isExpired: false,
    },
    relatedDecisions: [
      { id: "#7f3a2b-7", tool: "Edit file", verdict: "ALLOW" },
      { id: "#7f3a2b-6", tool: "Read docs", verdict: "ALLOW" },
    ],
  },
  "node-12": {
    decisionId: "d_7f3a2c-12",
    sequence: 12,
    status: "REVIEW",
    actionCommand: "policy_human_intervention_request",
    tool: "PolicyEngine",
    provider: "LAYA",
    model: "praxLaya-v1",
    riskLevel: "MEDIUM",
    riskScore: 0.50,
    semanticEvaluation: [
      { provider: "LAYA", score: 0.76, verdict: "REVIEW" },
      { provider: "TypeSafe", score: 0.70, verdict: "ALLOW" },
    ],
    policyDecision: {
      status: "Awaiting Operator Sign-off",
      requiresConfirmation: true,
      rulesActivated: ["DoubleVerification"],
      reasonCodes: ["REQUIRE_HUMAN_CONFIRMATION"],
      precedence: "Safety Precedence",
    },
    capability: {
      issued: false,
      statusText: "Pending human ticket",
      token: null,
      expiresAt: null,
    },
    reason: "External RFC query requires operational confirmation for internet egress.",
    evidenceTab: {
      groundingScore: 0.65,
      claimCount: 1,
      claims: ["Agent requested outbound network query to RFC catalog."],
      observationsUsed: ["network_egress_intent"],
      freshness: "live (14:32:24 UTC)",
    },
    receiptTab: {
      decisionId: "d_7f3a2c-12",
      sessionId: "7f3a2c",
      actionHash: "sha256:33ba17f001198547a4c7e",
      stateHash: "sha256:1099afcc8923a10582772",
      nonce: "non_110294b",
      signature: "hmac-sha256:4421aa80fbc193",
      hasValidHmac: true,
      expiresAt: "14:37:24 UTC",
      isExpired: false,
    },
    relatedDecisions: [
      { id: "#7f3a2b-11", tool: "Search web", verdict: "REVIEW" },
    ],
  },
};

export const INITIAL_LOGS = [
  { time: "14:32:01", level: "INFO", message: "Starting session 7f3a2c...." },
  { time: "14:32:01", level: "INFO", message: "Agent: CodingAgent | Goal: Fix authentication bug in the API" },
  { time: "14:32:18", level: "INFO", message: "Proposing action: git push origin main" },
  { time: "14:32:28", level: "INFO", message: "Evaluating with LAYA (praxLaya)... 0.81 ALLOW", highlight: "ALLOW" },
  { time: "14:32:41", level: "INFO", message: "Evaluating with TypeSafe (secondary)... 0.64 REVIEW", highlight: "REVIEW" },
  { time: "14:32:44", level: "WARN", message: "Policy requires human confirmation for this action", highlight: "WARN" },
];

export const INITIAL_EVENTS = [
  { seq: 1, type: "session.started", time: "14:32:01", detail: "Session 7f3a2c initialized with goal: Fix authentication bug in the API" },
  { seq: 2, type: "action.proposed", time: "14:32:01", detail: "Action 1: Analyze issue [LLM]" },
  { seq: 3, type: "policy.decided", time: "14:32:01", detail: "Policy: ALLOW (StandardPolicy)" },
  { seq: 4, type: "action.proposed", time: "14:32:12", detail: "Action 4: Read file: auth/middleware.py [Tool]" },
  { seq: 5, type: "capability.issued", time: "14:32:12", detail: "Capability cap_4102ba issued for read_file" },
  { seq: 6, type: "action.proposed", time: "14:32:18", detail: "Action 5: git push origin main [Branching Hub]" },
  { seq: 7, type: "evidence.evaluated", time: "14:32:20", detail: "Evidence count: 3, Grounding score: 0.72" },
  { seq: 8, type: "risk.assessed", time: "14:32:22", detail: "Risk Level: HIGH, Reason: Egress push to remote repository" },
  { seq: 9, type: "policy.decided", time: "14:32:28", detail: "Policy verdict: REQUIRE_HUMAN_CONFIRMATION" },
  { seq: 10, type: "approval.requested", time: "14:32:44", detail: "Operator sign-off requested for Action 5" },
];
